name: Status

on:
  push:
    branches:
      - "main"
  pull_request:

jobs:
  config:
    name: Validate ESPHome configuration
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-python@v5
        with:
          python-version: "3.14"
          cache: "pip"

      - run: pip install esphome

      - name: Validate ESPHome config
        run: esphome config cat-litter-box.yaml

  compile:
    name: Compile ESPHome build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-python@v5
        with:
          python-version: "3.14"
          cache: "pip"

      - run: pip install esphome

      - name: Compile ESPHome build
        run: esphome compile cat-litter-box.yaml
