name: Status

on:
  push:
    branches:
      - "main"
  pull_request:

jobs:
  config:
    name: Validate ESPHome configuration
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-python@v6
        with:
          python-version: "3.13"
          cache: "pip"

      - run: pip install -r requirements.txt

      - name: Validate ESPHome config
        run: esphome config cat-litter-box.yaml

  compile:
    name: Compile ESPHome build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-python@v6
        with:
          python-version: "3.13"
          cache: "pip"

      - run: pip install -r requirements.txt

      - name: Compile ESPHome build
        run: esphome compile cat-litter-box.yaml

  openscad:
    name: Build OpenSCAD project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: true

      - run: sudo apt-get update && sudo apt-get install openscad -y

      - run: openscad models/enclosure.scad -D 'renderQuality=8' -o models/enclosure.png --imgsize 1600,1600 && xdg-open models/enclosure.png

      - name: Archive code coverage results
        uses: actions/upload-artifact@v4
        with:
          name: OpenSCAD render
          path: models/enclosure.png
